### ISSUE TITLE
Using typeof to type a function parameter breaks highlighting

### ISSUE THREAD

**Issue by Tazmondo** [JohnnyMorganz/Luau.tmLanguage#6]
When declaring a function, using `typeof(something)` to type one of the parameters breaks the highlighting.
This does not occur in Studio.
While appearing minor here, depending on the theme settings, it can look a lot worse.

### Broken highlighting:
```lua
local x: any
x.foo = 20

local function func(header: typeof(Instance.new("Humanoid"))) end

local y: any
y.foo = 10
```
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/29681369/0d71b38b-e43d-4089-986e-98636bb07984)

### Correct highlighting:

```lua
local x: any
x.foo = 20

local function func(header: string) end

local y: any
y.foo = 10
```
![image](https://github.com/JohnnyMorganz/luau-lsp/assets/29681369/70c74b22-008f-48a2-ba86-38d10bd7ff2f)

**Comment by JohnnyMorganz** [comment]
Transferring to syntax highlighting repo.

This one is a bit of a pain to fix in TextMate given that it relies on balanced parentheses `()`, which is something regex cannot handle!

**Comment by alexmccord** [comment]
If it helps with debugging this, I did notice that this breaks when you use `typeof()` as the type annotation for the _last_ parameter. Meaning `function f(x: typeof(...), y)` is fine. You could also add a space after `)` to close `typeof(`, so `function f(x: typeof(...) )` is also fine.

**Comment by JohnnyMorganz** [comment]
Yeah we use a heuristic regex to determine when to terminate the regex: https://github.com/JohnnyMorganz/Luau.tmLanguage/blob/9f320add6dd099f99897a03c5e2ce3ca5f176d7f/Luau.YAML-tmLanguage#L310

Two parentheses together doesn't terminate (due to a function call inside of typeof).

There is probably a better way to structure the grammar, but i always find these changes viral (touch one thing and next thing you know you're rewriting the whole thing)

A workaround is to extract the typeof into a type alias.
